---
- name: Install pyenv requirements
  swupd:
    state: present
    name: "{{ item }}"
  with_items:
    - devpkg-bzip2
    - devpkg-libffi
    - devpkg-ncurses
    - devpkg-openssl
    - devpkg-readline
    - devpkg-sqlite-autoconf

- name: Download pyenv
  become: no
  git: 
    repo: https://github.com/pyenv/pyenv.git
    dest: "/home/{{ ansible_ssh_user }}/.pyenv"

- name: Install pipenv
  become: no
  pip:
    name: pipenv
    extra_args: --user
