---
- name: "Install base command lines tools"
  swupd:
    state: present
    name: "{{ item }}"
  with_items:
    - clr-network-troubleshooter
    - curl
    - git
    - htop
    - net-tools
    - sysadmin-basic
    - wget

- name: "Install zsh"
  swupd:
    state: present
    name: zsh

- name: "Set zsh as defualt"
  user:
    name: "{{ ansible_ssh_user }}"
    shell: /usr/bin/zsh

- name: "Clone oh-my-zsh repo"
  git:
    repo: "git://github.com/robbyrussell/oh-my-zsh.git"
    dest: "/home/{{ ansible_ssh_user }}/.oh-my-zsh"

- name: "Create new zs config from the template in the oh-my-zsh repo"
  copy:
    remote_src: yes
    src: "/home/{{ ansible_ssh_user }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "/home/{{ ansible_ssh_user }}/.zshrc"

