---
- name: check if pyenv installed
  stat:
    path: /home/{{ ansible_ssh_user }}/.pyenv
  register: pyenv_exists

- name: Download pyenv installer
  get_url:
    url: "https://pyenv.run"
    dest: /tmp/pyenv-install.sh
  when: pyenv_exists.stat.exists == False

- name: Install pyenv
  command: bash /tmp/pyenv-install.sh
  when: pyenv_exists.stat.exists == False
  args:
    creates: /home/{{ ansible_ssh_user }}/.pyenv

- name: Update pyenv
  command: ~/.pyenv/bin/pyenv update

- name: Install pipenv to user's home packages.
  pip:
    executable: pip3
    name: pipenv
    extra_args: --user
