---
- name: Install neovim
  snap:
    name: nvim
    classic: yes

- name: Install AstroNvim dependencies
  apt:
    name:
    - ripgrep
    - ncdu

- name: Install AstroNvim dependencies
  snap:
    name: node
    classic: yes

- name: Clone AstroNvim repo
  become: no
  git:
    repo: "https://github.com/AstroNvim/AstroNvim"
    dest: "/tmp/astronvim"

- name: Copy AstroNvim config
  become: no
  copy:
    src: "/tmp/astronvim/"
    dest: "/home/{{ ansible_ssh_user }}/.config/nvim/"
    remote_src: yes
    backup: yes

- name: Change `.local/share/nvim/site` ownership to ansible user
  file:
    path: "/home/{{ ansible_ssh_user }}/.local/share/nvim/site"
    state: directory
    recurse: yes
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Run nvim PackerSync
  become: no
  shell: /snap/bin/nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
