---
- name: Install neovim
  snap:
    name: nvim
    classic: yes

- name: Download JetBrainsMono Nerd Font
  become: no
  get_url:
    url: https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh
    dest: "/tmp/jetbrains-font-installer.sh"
    mode: "755"

- name: Install JetBrainsMono Nerd Font
  become: no
  shell: /tmp/jetbrains-font-installer.sh

- name: Install AstroNvim dependencies
  apt:
    name:
    - ripgrep
    - ncdu

- name: Install AstroNvim dependencies
  snap:
    name: node
    classic: yes

- name: Clone AstroNvim repo
  become: no
  git:
    repo: "https://github.com/AstroNvim/AstroNvim"
    dest: "/tmp/astronvim"

- name: Copy AstroNvim config
  become: no
  copy:
    src: "/tmp/astronvim"
    dest: "/home/{{ ansible_ssh_user }}/.config/nvim"
    backup: yes

- name: Run nvim PackerSync
  become: no
  shell: /snap/bin/nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
