---
- name: Install zsh
  apt:
    name:
      - zsh
    state: present
    update_cache: yes

- name: Set zsh as defualt
  user:
    name: "{{ ansible_ssh_user }}"
    shell: /bin/zsh

- name: Check if oh-my-zsh exists
  stat:
    path: "/home/{{ ansible_ssh_user }}/.oh-my-zsh/"
  register: ohmyzsh_installed

- name: Download install.sh for oh-my-zsh
  become: no
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "/tmp/ohmyzsh-install.sh"
    mode: "755"
  when: not ohmyzsh_installed.stat.exists

- name: Install oh-my-zsh
  become: no
  shell:
    cmd: "/tmp/ohmyzsh-install.sh"
    stdin: "y"
  when: not ohmyzsh_installed.stat.exists

- name: Copy r4g-robbyrussel theme
  become: no
  copy:
    src: r4g-robbyrussel.zsh-theme
    dest: "/home/{{ ansible_ssh_user }}/.oh-my-zsh/themes/r4g-robbyrussell.zsh-theme"
    backup: yes

- name: Create new zsh config from the template
  become: no
  template:
    src: zsh.conf.j2
    dest: "/home/{{ ansible_ssh_user }}/.zshrc"
    backup: yes
