---
- name: "Configure ClearLinux machine"
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  roles:
    - apps
    - ballast
    - cli-tools
    - gcloud
    - python
    - settings

