---
- name: "Add firefox keyboard shortcut binding"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
    value: "'<Primary><Alt>f'"

- name: "Add firefox keyboard shortcut command"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
    value: "'firefox -p'"

- name: "Add firefox keyboard shortcut name"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
    value: "'firefox'"

- name: Install Firefox
  snap:
    name: firefox

- name: Install chromium
  snap:
    name: chromium
