---
- name: Install Juju
  snap:
    name: juju
    classic: yes

- name: Install kubectl
  snap:
    name: kubectl
    classic: yes

- name: Install google-cloud utils
  snap:
    name: google-cloud-sdk
    classic: yes

- name: Install Remmina
  snap:
    name: remmina
