---
- name: Install Slack, Thunderbird and Telegram
  become: no
  flatpak:
    state: present
    method: user
    name: "{{ item }}"
    remote: flathub
  loop:
    - com.slack.Slack
    - org.mozilla.Thunderbird
    - org.telegram.desktop

