---
- name: Install required system packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: yes

- name: Install Docker
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

- name: Enable Docker in systemctl
  systemd:
    name: docker
    enabled: yes
    state: started
  
- name: Add user to docker group
  user:
    state: present
    name: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    groups: docker
    append: yes
  become: yes

