---
- name: Install required system packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: yes

- name: Install Docker
  apt:
     name:
       - docker-ce
       - docker-ce-cli
       - containerd.io
     state: present
     update_cache: yes

- name: Add user to docker group
  user:
    state: present
    name: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    groups: docker
    append: yes
