---
- name: Install all apps with flatpak
  become: no
  flatpak:
    state: present
    method: user
    name: "{{ item }}"
    remote: flathub
  loop:
    - com.sublimetext.three

- name: Download script to install JetBrains Toolbox
  become: no
  git:
    repo: https://github.com/nagygergo/jetbrains-toolbox-install.git
    dest: "/home/{{ ansible_ssh_user }}/.jetbrains-toolbox"
  notify:
    - Install JetBrains Toolbox

- name: Set Jetbrains-Toolbox as desktop app
  template:
    src: jetbrains-toolbox.desktop
    dest: /home/{{ ansible_ssh_user }}/.local/share/applications
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: "0664"
