---
- name: Install all apps with flatpak
  become: no
  flatpak:
    state: present
    method: user
    name: "{{ item }}"
    remote: flathub
  loop:
    - com.sublimetext.three

- name: Download script to install JetBrains Toolbox
  become: no
  git:
    repo: https://github.com/nagygergo/jetbrains-toolbox-install.git
    dest: "/home/{{ ansible_ssh_user }}/.jetbrains-toolbox"
  notify:
    - Install JetBrains Toolbox

