---
- name: Docker
  import_tasks: docker.yml

- name: Virtualization
  import_tasks: virtualization.yml

- name: Cloud tools
  import_tasks: cloud_tools.yml

- name: Preparation
  import_tasks: prep.yml

- name: Communication
  import_tasks: communication.yml

- name: Cloud storage
  import_tasks: storage.yml

- name: IDLE
  import_tasks: idle.yml

- name: Others
  import_tasks: others.yml

